/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals;

public enum Planeta {

    MERCURY (3.303e+23, 2.4397e6),
    VENUS   (4.869e+24, 6.0518e6),
    EARTH   (5.976e+24, 6.37814e6),
    MARS    (6.421e+23, 3.3972e6),
    JUPITER (1.9e+27,   7.1492e7),
    SATURN  (5.688e+26, 6.0268e7),
    URANUS  (8.686e+25, 2.5559e7),
    NEPTUNE (1.024e+26, 2.4746e7);

    public static double G = 6.67300e-11;

    private final double masa;
    private final double radio;

    Planeta(double kilos, double metros) {
        this.masa = kilos;
        this.radio = metros;
    }

    public double getMasa () {
        return masa;
    }

    public double getRadio() {
        return radio;
    }

    private double gravedadSuperficie (){
        return (G * this.getMasa()) / (this.getRadio() * this.getRadio() );
    }

    private double gravedadSuperficie (Planeta planeta) {
        return (G * planeta.getMasa()) / ( planeta.getRadio() * planeta.getRadio());
    }

    private double masaTierra(double peso){
        return peso / this.gravedadSuperficie(EARTH);
    }

    public double pesoSuperficie(double pesoHumano) {
    return masaTierra(pesoHumano) * this.gravedadSuperficie() ;
    }


}
